version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      
  git: 
    image: alpine/git 
    container_name: git 
    entrypoint: /bin/sh -c "git config --global user.name 'Li Peishan' && git config --global user.email '2102934@sit.singaporetech.edu.sg' && tail -f /dev/null"
    
  flask-app:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      
  # SonarQube service configuration
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"  
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube  
      - SONARQUBE_JDBC_PASSWORD=sonarqube  

  # MySQL database service configuration
  db:
    image: mysql:latest   
    environment:
      MYSQL_ROOT_PASSWORD: 2102934
      MYSQL_DATABASE: sonarqube  
      MYSQL_USER: sonarqube  
      MYSQL_PASSWORD: sonarqube  

volumes:
  jenkins_data:
    driver: local